In [42]:
import pandas as pd

In [43]:
dataset = pd.read_csv("Downloads\cancer patient data sets.csv")

In [44]:
dataset

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,P995,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
996,996,P996,37,2,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
997,997,P997,25,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
998,998,P998,18,2,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
999,999,P999,47,1,6,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High

In [45]:
y = dataset['Level']

In [46]:
y = pd.get_dummies(y)

In [47]:
import seaborn as sns

In [48]:
y

     High  Low  Medium
0       0    1       0
1       0    0       1
2       1    0       0
3       1    0       0
4       1    0       0
..    ...  ...     ...
995     1    0       0
996     1    0       0
997     1    0       0
998     1    0       0
999     1    0       0

[1000 rows x 3 columns]

In [49]:
dataset.drop(['index','Patient Id'],axis=1,inplace=True)

In [50]:
dataset.columns

Index(['Age', 'Gender', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [51]:
x = dataset[['Age', 'Gender', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring']]

In [52]:
x.shape

(1000, 23)

In [53]:
x

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring
0,33,1,2,4,5,4,3,2,2,4,...,4,3,4,2,2,3,1,2,3,4
1,17,1,3,1,5,3,4,2,2,2,...,3,1,3,7,8,6,2,1,7,2
2,35,1,4,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2
3,37,1,7,7,7,7,6,7,7,7,...,8,4,2,3,1,4,5,6,7,5
4,46,1,6,8,7,7,7,6,7,7,...,9,3,2,4,1,4,2,4,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,7,7,6,7,7,...,7,5,3,2,7,8,2,4,5,3
996,37,2,6,8,7,7,7,6,7,7,...,7,9,6,5,7,2,4,3,1,4
997,25,2,4,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2
998,18,2,6,8,7,7,7,6,7,7,...,9,3,2,4,1,4,2,4,2,3
999,47,1,6,5,6,5,5,4,6,7,...,8,8,7,9,2,1,4,6,7,2

In [54]:
y.shape

(1000, 3)

In [55]:
from keras import Sequential

In [56]:
model = Sequential()

In [57]:
model.get_config()

{'name': 'sequential_1', 'layers': []}

In [60]:
from keras.layers import Dense

In [61]:
# layer 1
model.add(  
        Dense(
                units=6 ,  
                input_dim=23 , 
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="relu"
        )  
)

In [62]:
# layer 2
model.add(  
        Dense(
                units=7,
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="relu"
        )  
)

In [63]:
# layer 3
model.add(  
        Dense(
                units=5,
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="relu"
        )  
)

In [64]:
# layer 4 : output layer
model.add(  
        Dense(
                units=3,
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="softmax"
        )  
)

In [65]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 6)                 144

 dense_5 (Dense)             (None, 6)                 42

 dense_6 (Dense)             (None, 7)                 49

 dense_7 (Dense)             (None, 5)                 40

 dense_8 (Dense)             (None, 3)                 18

=================================================================
Total params: 293
Trainable params: 293
Non-trainable params: 0
_________________________________________________________________

In [66]:
model.compile(loss="categorical_crossentropy")

In [67]:
model.fit(x, y, epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 2ms/step - loss: 1.0981
Epoch 2/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0976
Epoch 3/20
32/32 [==============================] - 0s 3ms/step - loss: 1.0972
Epoch 4/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0970
Epoch 5/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0968
Epoch 6/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0966
Epoch 7/20
32/32 [==============================] - 0s 3ms/step - loss: 1.0965
Epoch 8/20
32/32 [==============================] - 0s 3ms/step - loss: 1.0963
Epoch 9/20
32/32 [==============================] - 0s 3ms/step - loss: 1.0962
Epoch 10/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0961
Epoch 11/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0961
Epoch 12/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0960
Epoch 13/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0960
Epoch 14/20
32/32 [==============================] - 0s 3ms/step - loss: 1.0959
Epoch 15/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0959
Epoch 16/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0960
Epoch 17/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0959
Epoch 18/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0959
Epoch 19/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0959
Epoch 20/20
32/32 [==============================] - 0s 2ms/step - loss: 1.0959

In [68]:
y_test = model.predict([[5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5]])

1/1 [==============================] - 0s 99ms/step

In [69]:
if(y_test[0][0]>y_test[0][1] and y_test[0][0]>y_test[0][2]):
    print("Low chance of cancer")
elif(y_test[0][1]>y_test[0][0] and y_test[0][1]>y_test[0][2]):
    print("Medium chance of cancer")
else:
    print("High chance of cancer")

Low chance of cancer